let main=[
    {										
name:"Switch Replacement",
rating:"4.81(5.5K)",
special:"5 mins",
price:79,
a:"₹30 off 2nd service onwards 1 Replacement of single switch",
b:"Spare parts cost not included",
c:"",
    },
    { 

name:"Socket Replacement",
rating:"4.82(3.2K)",	
price:109,
special:"10 mins",
a:"₹30 off 2nd service onwards	Replacement of single socket unit",
b:"Spare parts' cost not included",
c:"",
    },
    {
name:"Switchboard repair",
rating:"4.82(40.8K)",
price:110,
special:"30 mins",
a:"₹41 off 2nd service onwards	Labor charges for Repair of one switchboard only.",
b:"Spare parts are sourced at an additional cost (market rate)",
c:""
    },
    { 
name:"Fan repair",
rating:"4.78(47.4K)",
price:199,
special:"30 mins",
a:"₹30 off 2nd service onwards	Labor charges for repair of ceiling", 
b:"wall or exhaust fan	Spare parts are sourced at an additional cost (market rate)",
c:"",
    	},
        { 
        
name:"Tubelight Installation/Repair",
rating:"4.84(31.7K)",
price:129,
special:"30 mins",
a:"₹30 off 2nd service onwards	Labor charges for installation of one tube light",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
        },
        { 
name:"Ceiling Fan Installation",
rating:"4.83(27.4K)",
price:148,
special:"30 mins",
a:"₹29 off 2nd service onwards	Labor charges for Installation of ceiling", 
b:"exhaust or wall fan	Spare parts are sourced at an additional cost (market rate)",
c:"",
        },
        { 										
name:"AC switchbox installation",
rating:"4.79(5.5K)",
price:369,
special:"30 mins",
a:"₹40 off 2nd service onwards	Labor charges for Installation of one AC switchbox",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
        },
        {

name:"Switchboard installation",
rating:"4.81(16.4K)",
price:279,
special:"30 mins",
a:"₹30 off 2nd service onwards	Labor charges for Installation of one Switchboard",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
        	},
            {


            	
name:"Switchboard repair",
rating:"4.82(40.8K)",
price:110,
special:"30 mins",
a:"₹41 off 2nd service onwards	Labor charges for Repair of one switchboard only.",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
            	},
{ 
name:"Switch/socket replacement",
rating:"4.82(41.7K)",
price:109,
special:"30 mins",
a:"₹30 off 2nd service onwards",
b:"Replacement of one switch/ socket/ combination unit	Spare parts are sourced at an additional cost (market rate)",
c:"",
	},
    {
name:"15+ Amp Switch Box",
rating:"4.81(2.1K)",
price:349,
special:"10 mins",
a:"Add	Labor charges for Installation of 1 heavy switchboard",
b:"(15+ amp)Spare parts are sourced at an additional cost (market rate)",
c:"",
    },
    {										
name:"Ceiling fan regulator replacement",
rating:"4.80(19.8K)",
price:99,
special:"30 mins",
a:"30 off 2nd service onwards	Labor charges for Replacement of one ceiling fan regulator",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
    },
    {

name:"Decorative ceiling fan installation",
rating:"4.8(524)",
price:469,
special:"60 mins",
a:"Labor charges for Installation of fan with in-built light, music etc.",
b:"Spare parts are sourced at an additional cost (market rate)",
c:""
    },
{ 	
name:"Ceiling Fan Installation",
rating:"4.83(27.4K)",
price:148,
special:"30 mins",
a:"₹29 off 2nd service onwards	Labor charges for Installation of ceiling",
b:"exhaust or wall fan	Spare parts are sourced at an additional cost (market rate)",
c:"",
},
{
name:"Fan repair",
rating:"4.78(47.4K)",
price:199,
special:"30 mins",
a:"₹30 off 2nd service onwards	Labor charges for repair of ceiling", 
b:"wall or exhaust fan	Spare parts are sourced at an additional cost (market rate)",
c:"",
	},
    {
name:"Fan replacement",
rating:"4.86(8.2K)",
price:239,
special:"60 mins",
a:"₹30 off 2nd service onwards	Labor charges for Replacement of ceiling",
b:"exhaust or wall fan	Spare parts are sourced at an additional cost (market rate)",
c:"",
    },
    { 
name:"Fan uninstallation",
rating:"4.88(4.1K)",
price:139,
special:"30 mins",
a:"Labor charges for uninstallation of ceiling", 
b:"exhaust or wall fan	Spare parts are sourced at an additional cost (market rate)",
c:"",
    	},
        
{ 									
name:"Bulbs installation (upto 5 bulbs)",
rating:"4.81(7.5K)",
price:139,
special:"1 hr 30 mins",
a:"Labor charges for installation of up to five bulbs",
b:"Spare parts are sourced at an additional cost (market rate)",	
c:""
},
{
name:"Bulb holder installation",
rating:"4.84(11.7K)",
price:119,
special:"20 mins",
a:"₹30 off 2nd service onwards	Labor charges for installation of one bulb holder",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
},
{
name:"False ceiling light installation",
rating:"4.84(14.4K)",
price:219,
special:"30 mins",
a:"Installation of one decorative wall light",
b:"ceiling light or bed lamp	Spare parts are sourced at an additional cost (market rate)",
c:"",
	},
    	{ 

name:"Tubelight Installation/Repair",
rating:"4.84(31.7K)",
price:129,
special:"30 mins",
a:"₹30 off 2nd service onwards	Labor charges for installation of one tube light",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
        },
        {
name:"Chandelier installation (upto 6 bulbs)",
rating:"4.84(2K)",
price:549,
special:"60 mins",
a:"Labor charges for installation of one chandelier with up to six bulbs",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
        },
        {
name:"Chandelier installation (more than 6 bulbs)",
rating:"4.70(228)",
price:1099,
special:"1 hr 30 mins",
a:"Labor charges for installation of one chandelier with more than 6 bulbs",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
        },
        {									
name:"Modular Retrofit Smart Switches",
rating:"4.80(43)",
price:150,
special:"15 mins",
a:"Labor charges for installation & configuration of one smart modular switch",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
        },
    { 
name:"Smart appliance controller(Touch Panel/Smart plug)",
rating:"4.80(43)",
price:199,
special:"15 mins",
a:"Labor charges for installation & configuration of one smart plug/ touch panel",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
    	},
        {	
name:"Converter Retrofit Wi-Fi Smart Switches",
rating:"4.76(52)",
price:199,
special:"15 mins",
a:"Labor charges for installation & configuration of one smart converter switch",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
        	},
            { 
name:"EV Charger Installation (2 Wheeler)",
rating:"4.94(24)",
price:750,
special:"1 hr 30 mins",
a:"Installation of 1 charging station (at home) for a two wheeler EV",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
            	},
      {        
name:"WiFi CCTV installation",
rating:"4.70(1.3K)",
price:299,
special:"30 mins",
a:"Labor charges for installation of 1 wifi CCTV",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
      	},	
        {
name:"Home video bell",
rating:"4.73(54)",
price:600,
special:"45 mins",
a:"Labor charges for installation of 1 home video bell",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
        },
        {										
name:"3 Phase changeover switch installation",
rating:"4.80(511)",
price:369,
special:"30 mins",
a:"Labor charges for installation of one 3-phase changeover switch",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
        },  
        {

        
name:"MCB fuse replacement",
rating:"4.78(4.4K)",
price:119,
special:"30 mins",
a:"Labor charges for replacement of one MCB fuse",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
        	},
        {
name:"Single pole MCB installation",
rating:"4.78(3.4K)",
price:119,
special:"1 hr 30 mins",
a:"Labor charges for installation of single pole MCB",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
        	},
            {
            	
name:"Sub meter installation",
rating:"4.81(538)",
price:319,
special:"60 mins",
a:"Labor charges for installation of one sub-meter with minor wiring work",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
            	},	
                {
										
name:"Single battery inverter installation",
rating:"4.76(4.4K)",
price:485,
special:"1 hr 30 mins",
a:"Labor charges for installation of single battery inverter",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
                },
                {
name:"Double battery inverter installation",
rating:"4.65(496)",
price:575,
special:"1 hr 30 mins",
a:"Labor charges for installation of double battery inverter",
b:"Spare parts are sourced at an additional cost (market rate)",
c:"",
                },
                {
name:"Inverter servicing",
rating:"4.71(10.1K)",
price:249,
special:"30 mins",
a:"Labor charges for servicing of one single/double battery inverter",b:"Spare parts are sourced at an additional cost (market rate)",c:""},	
{name:"Stabilizer installation",rating:"4.82(2.4K)",price:179,special:"30 mins",a:"Labor charges for installation of one stabilizer unit",b:"Spare parts are sourced at an additional cost (market rate)",c:""},
									
{name:"TV installation (up to 48 inches)",rating:"4.84	(6.9K)",price:599,special:"30 mins",a:"Labor charges for installation or uninstallation of one TV set",b:"Spare parts are sourced at an additional cost (market rate)",c:""},	
{name:"TV installation (above 48 inches)",rating:"4.81	(2.6K)"	,price:750,special:"60 mins",a:"Labor charges for installation or uninstallation of one TV set",b:"Spare parts are sourced at an additional cost (market rate)",c:""},
{name:"TV uninstallation",rating:"4.84	(2.3K)",price:189,special:"30 mins",a:"Labor charges for installation or uninstallation of one TV set",b:"Spare parts are sourced at an additional cost (market rate)",c:""	},

{name:"Mini home theater installation",rating:"4.69	(1.1K)",price:319,special:"1 hr 30 mins",a:"Installation of a mini home theatre with wiring from TV to speaker",b:"Spare parts are sourced at an additional cost (market rate)",c:""},

{name:"Stabilizer installation",rating:"4.82	(2.4K)",price:179,special:"30 mins",a:"Labor charges for installation of one stabilizer unit",b:"Spare parts are sourced at an additional cost (market rate)",c:""},	
									
{name:"New internal wiring (per 5m)",rating:"4.76	(4K)",price:249,special:"60 mins",a:"Concealed conduit internal wiring for a new connection",b:"Spare parts and wires are procured at an additional cost (market rate)",c:""},	
{name:"New wiring with casing (per 5m)",rating:"4.77	(5K)",price:349,special:"60 mins",a:"Wiring with outer casing and capping for a single connection",b:"Spare parts and wires are procured at an additional cost (market rate)",c:""},	
{name:"New wiring without casing (per 5m)",rating:"4.75	(3.6K)",price:129,special:"30 mins",a:"Wiring without outer casing for a single connection",b:"Spare parts and wires are procured at an additional cost (market rate)",c:""},											
{name:"Door bell installation",rating:"4.81	(4.2K)",price:109,special:"30 mins",a:"₹30 off 2nd service onwards	Labor charges for installation of one doorbell",b:"Spare parts are sourced at an additional cost (market rate)",c:""},	
{name:"Door bell replacement",rating:"4.83	(4.6K)",price:109,special:"30 mins",a:"₹30 off 2nd service onwards	Labor charges for replacement of one doorbell",b:"Spare parts are sourced at an additional cost (market rate)",c:""},										
{name:"Custom repair/installation",rating:"4.79	(21.1K)",price:179,special:"10 mins",a:"Actual Price Based on Scope of Work and Rate Card.",b:"Visitation charges to be adjusted in the final invoice",c:""},		
{name:"At home consultation for major work",rating:"4.71	(4.5K)",price:149,special:"10 mins",a:"Includes inspection charges",b:"Actual prices based on scope of work and rate card",c:""}		

]										